<a href="https://colab.research.google.com/github/wizardMati/expotraintelos/blob/master/sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
np.random.seed(10)
iris = datasets.load_iris()
wine = datasets.load_wine()

In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [4]:
iris_data = iris.data
iris_target = iris.target
wine_data = wine.data
wine_target = wine.target

In [5]:
iris_data_test, iris_data_train, iris_target_test, iris_target_train = train_test_split(iris_data, iris_target, test_size=0.2)
wine_data_test, wine_data_train, wine_target_test, wine_target_train = train_test_split(wine_data, wine_target, test_size=0.2)

In [6]:
print(iris_data_test.shape)
print(iris_data_train.shape)
print(iris_target_test.shape)
print(iris_target_train.shape)

(120, 4)
(30, 4)
(120,)
(30,)


In [7]:
print(wine_data_test.shape)
print(wine_data_train.shape)
print(wine_target_test.shape)
print(wine_target_train.shape)

(142, 13)
(36, 13)
(142,)
(36,)


In [8]:
models = {
     "Logistic Regression": LogisticRegression(max_iter=200),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42)
}

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
for name, model in models.items():
    model.fit(iris_data_train, iris_target_train)

    train_pred = model.predict(iris_data_train)
    test_pred = model.predict(iris_data_test)

    train_acc = accuracy_score(iris_target_train, train_pred)
    test_acc = accuracy_score(iris_target_test, test_pred)

    print(f"\n{name}")
    print(f"Accuracy train: {train_acc:.3f}")
    print(f"Accuracy test:  {test_acc:.3f}")


Logistic Regression
Accuracy train: 0.933
Accuracy test:  0.892

KNN
Accuracy train: 1.000
Accuracy test:  0.942

Decision Tree
Accuracy train: 1.000
Accuracy test:  0.950


In [10]:
for name, model in models.items():
    model.fit(wine_data_train, wine_target_train)

    train_pred = model.predict(wine_data_train)
    test_pred = model.predict(wine_data_test)

    train_acc = accuracy_score(wine_target_train, train_pred)
    test_acc = accuracy_score(wine_target_test, test_pred)

    print(f"\n{name}")
    print(f"Accuracy train: {train_acc:.3f}")
    print(f"Accuracy test:  {test_acc:.3f}")


Logistic Regression
Accuracy train: 1.000
Accuracy test:  0.951

KNN
Accuracy train: 0.722
Accuracy test:  0.634

Decision Tree
Accuracy train: 1.000
Accuracy test:  0.873


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
model = LogisticRegression(max_iter=200)
model.fit(iris_data_train, iris_target_train)

pred = model.predict(iris_data_test)

print(confusion_matrix(iris_target_test, pred))
print(classification_report(iris_target_test, pred))

[[40  0  0]
 [ 0 36  1]
 [ 0 12 31]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.75      0.97      0.85        37
           2       0.97      0.72      0.83        43

    accuracy                           0.89       120
   macro avg       0.91      0.90      0.89       120
weighted avg       0.91      0.89      0.89       120

